classes:
- system.linux.system.repo.docker_legacy
- system.linux.system.repo.mcp.extra
- system.linux.system.repo.mcp.apt_mirantis.ubuntu
- system.linux.system.repo.mcp.apt_mirantis.saltstack_2016_3
- system.kubernetes.pool.cluster
- system.salt.minion.cert.k8s_client
- system.salt.minion.cert.etcd_client
- cluster.mitroko.infra
parameters:
  _param:
    kubernetes_calicoctl_image: docker-prod-local.artifactory.mirantis.com/mirantis/projectcalico/calico/ctl:latest
    kubernetes_calico_image: docker-prod-local.artifactory.mirantis.com/mirantis/projectcalico/calico/node:latest
    kubernetes_calico_cni_image: docker-prod-local.artifactory.mirantis.com/mirantis/projectcalico/calico/cni:latest
    kubernetes_hyperkube_image: docker-prod-local.artifactory.mirantis.com/mirantis/kubernetes/hyperkube-amd64:v1.8.5-4
  docker:
    host:
      pkgs:
        - docker-engine=1.12.6-0~ubuntu-xenial
        - python-docker
  kubernetes:
    pool:
      network:
        no_default_pools: false
        etcd:
          ssl:
            enabled: True
        image: ${_param:kubernetes_calico_image}
        calicoctl:
          image: ${_param:kubernetes_calicoctl_image}
        cni:
          image: ${_param:kubernetes_calico_cni_image}
    common:
      hyperkube:
        image: ${_param:kubernetes_hyperkube_image}
  linux:
    system:
      package:
        docker-engine:
          version: 1.12.6-0~ubuntu-xenial
          hold: true
      kernel:
        sysctl:
          # The default operating system limits on mmap counts is likely to be too low, which may result in out of memory exceptions.
          vm.max_map_count: 262144
    network:
      interface:
        eth1:
          mtu: 9000
          enabled: true
          type: slave
          proto: manual
          name: ${_param:primary_first_nic}
          master: bond0
        eth2:
          mtu: 9000
          enabled: true
          type: slave
          proto: manual
          name: ${_param:primary_second_nic}
          master: bond0
        bond0:
          mtu: 9000
          enabled: true
          proto: manual
          type: bond
          use_interfaces:
          - ${_param:primary_first_nic}
          - ${_param:primary_second_nic}
          slaves: ${_param:primary_first_nic} ${_param:primary_second_nic}
          mode: active-backup
        bond0.1:
          mtu: 9000
          name: bond0.${_param:control_vlan}
          enabled: true
          proto: static
          type: vlan
          use_interfaces:
          - bond0
          address: ${_param:single_address}
          netmask: ${_param:control_network_netmask}
        bond0.2:
          mtu: 9000
          name: bond0.${_param:tenant_vlan}
          enabled: true
          proto: static
          type: vlan
          use_interfaces:
          - bond0
          address: ${_param:tenant_address}
          netmask: ${_param:tenant_network_netmask}
