
parameters:
  _param:
    salt_minion_ca_host: ${_param:infra_config_hostname}.${_param:cluster_domain}
    salt_minion_ca_authority: salt_master_ca

    # kubernetes settings
    kubernetes_admin_user: admin
    kubernetes_admin_password: 2DAq9C2TsSZIV5Dg
    kubernetes_admin_token: v312OFFZMpu6M0DARgBQv5Qaxz4F3NQm
    kubernetes_kubelet_token: wUJVsEPdxbFxp857wICefSNCKaWFEUpu
    kubernetes_kube-proxy_token: Fve7hyedkBh8EnnZesZXEJcCwAe8Qcwj
    kubernetes_scheduler_token: Sey8ec2ru31quR4bqFCpXgSNYUbfc8f3
    kubernetes_controller-manager_token: hodC2uBM0Aw7bCZqBGo1odzejJ4xyMcD
    kubernetes_dns_token: xD7iUbEhE2WJPmlEMiwdtKYrdgilCC5M
    etcd_initial_token: 3IGogg5jMsyj5fkawPG4O1uejVEQeyub

    # addresses and hostnames
    kubernetes_internal_api_address: 10.254.0.1
    kubernetes_control_hostname: ctl
    kubernetes_control_address: 10.0.1.10
    kubernetes_control_node01_hostname: ctl01
    kubernetes_control_node02_hostname: ctl02
    kubernetes_control_node03_hostname: ctl03
    kubernetes_control_node01_address: 10.0.1.11
    kubernetes_control_node02_address: 10.0.1.12
    kubernetes_control_node03_address: 10.0.1.13

    cluster_vip_address: ${_param:kubernetes_control_address}
    cluster_local_address: ${_param:single_address}

    # etcd stuff
    cluster_node01_hostname: ${_param:kubernetes_control_node01_hostname}
    cluster_node01_address: ${_param:kubernetes_control_node01_address}
    cluster_node01_port: 4001
    cluster_node02_hostname: ${_param:kubernetes_control_node02_hostname}
    cluster_node02_address: ${_param:kubernetes_control_node02_address}
    cluster_node02_port: 4001
    cluster_node03_hostname: ${_param:kubernetes_control_node03_hostname}
    cluster_node03_address: ${_param:kubernetes_control_node03_address}
    cluster_node03_port: 4001

    kubernetes_virtlet_enabled: False
    # calico
    calico_private_network: 192.168.0.0
    calico_private_netmask: 24
    kubernetes_control_node01_tenant_address: 172.16.11.11
    kubernetes_control_node02_tenant_address: 172.16.11.12
    kubernetes_control_node03_tenant_address: 172.16.11.13

  linux:
    network:
      host:
        ctl:
          address: ${_param:kubernetes_control_address}
          names:
          - ${_param:kubernetes_control_hostname}
          - ${_param:kubernetes_control_hostname}.${_param:cluster_domain}
        ctl01:
          address: ${_param:kubernetes_control_node01_address}
          names:
          - ${_param:kubernetes_control_node01_hostname}
          - ${_param:kubernetes_control_node01_hostname}.${_param:cluster_domain}
        ctl02:
          address: ${_param:kubernetes_control_node02_address}
          names:
          - ${_param:kubernetes_control_node02_hostname}
          - ${_param:kubernetes_control_node02_hostname}.${_param:cluster_domain}
        ctl03:
          address: ${_param:kubernetes_control_node03_address}
          names:
          - ${_param:kubernetes_control_node03_hostname}
          - ${_param:kubernetes_control_node03_hostname}.${_param:cluster_domain}
